esphome:
  name: exampleradoneyeplus2
  platform: ESP32
  board: nodemcu-32s
  includes:
    - radoneye_rd200_sensor.h

wifi:
  ssid: "XXX"
  password: "YYY"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "RadonEyePlus2 Fallback Hotspot"
    password: "radoneye+2"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
  - platform: custom
    lambda: |-
      auto my_radon = new RadonEye("xx:xx:xx:xx:xx:xx");
      App.register_component(my_radon);
      return {my_radon->radon_10min, my_radon->radon_day, my_radon->radon_month, my_radon->radon_puls, my_radon->radon_puls10};
    sensors:
      - name: "Radon now"
        unit_of_measurement: Bq
        accuracy_decimals: 0
      - name: "Radon day"
        unit_of_measurement: Bq
        accuracy_decimals: 0
      - name: "Radon month"
        unit_of_measurement: Bq
        accuracy_decimals: 0
      - name: "Radon puls"
        unit_of_measurement: Bq
        accuracy_decimals: 0
      - name: "Radon puls10"
        unit_of_measurement: Bq
        accuracy_decimals: 0
